### PR TITLE
Added option to follow system dark mode

### PR DESCRIPTION
**Pull request by mrclsu**

### CODE REVIEW

**Comment by OMIsie11** [comment]
Thank You for this PR 😄  
I will check it when I will have a moment, but looks like those changes are nice 😃

**Comment by mrclsu** [comment]
I've changed the preference key used for dark mode to prevent the app from crashing when a user upgrades to this version.
Also oops I didn't mean to close the issue. 😄

**Comment by OMIsie11** [comment]
Okay, I checked it.
I found some small things (strings from old Dark mode preference to deletion and unused import), but I will fix it myself because I see that I need to fix one thing connected with server data (Cores functionality not working).
I should rewrite whole data layer to don't have problems like that in future, I have to update this repo. Even that small app have technical debt and bad decisions 😞 
I will add a small "Thank You" section in application and repo Readme and link to Your profile. If You would like some specific link (not to Your GitHub profile) please let me know 😃 
Thank You for Your work! 😄

**Comment by mrclsu** [comment]
Yeah, I know the feeling a lot of my small projects have technical debt.
Also, thanks for the attribution (a github profile like is fine btw).

**Comment by OMIsie11** [comment]
Okay, so attributions are live in app and repo 🙂

**Pull request merged**
